# Generated by Django 4.1.5 on 2023-06-17 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="likePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=500)),
                ("user_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 17, 17, 48, 23, 522502)
            ),
        ),
    ]
